Feat/section tag
wowdop/profile-group pull request #53
Opened 2022-09-04 14:09 UTC by Alez05

2022-09-04 14:17 UTC, flivanov92 approved these changes
👍

2022-09-05 10:56 UTC, antonia2203 reviewed
💯

2022-09-05 12:25 UTC, MariaTeo requested changes
you also committed more files than section-tag.pug. at least add some content in the empty tag

2022-09-05 12:25 UTC, MariaTeo commented on src/alez05/article-tag.pug
> +      article
this tag is empty.

2022-09-05 12:29 UTC, marianzburlea requested changes

2022-09-05 12:29 UTC, marianzburlea commented on src/alez05/section-tag.pug
> +    p The World Wide Fund for Nature (WWF) is an international organization working on issues regarding the conservation, research and restoration of the environment, formerly named the World Wildlif
8 and 9 should be children to **section**, that's why we use the tag, to wrap other tags

2022-09-05 12:29 UTC, marianzburlea commented on src/alez05/section-tag.pug
> +    h2 WWF's Symbol
11 to 20 should be inside the **section** tag

2022-09-05 12:29 UTC, marianzburlea commented on src/alez05/article-tag.pug
> +      h2 Edward Newgate
h2 and p, inside **article**

2022-09-05 12:29 UTC, marianzburlea commented on src/alez05/iframe.pug
> +      src="https://6portals.com" title="Buy the best merch in here"
src and title on separate lines
```
src="asdas"
title="aasdasd"
```

2022-09-05 14:57 UTC, Vivy approved these changes
nice 1

2022-09-05 15:54 UTC, MariaTeo approved these changes

2022-09-05 16:01 UTC, marianzburlea approved these changes
💯

2022-09-05 19:55 UTC, merged