feat: played with mark tag
wowdop/profile-group pull request #96
Opened 2022-09-06 15:51 UTC by Alez05

fix #95

2022-09-06 15:55 UTC, flivanov92 approved these changes
👍

2022-09-06 16:07 UTC, antonia2203 approved these changes
💯

2022-09-06 16:13 UTC, MariaTeo requested changes

2022-09-06 16:13 UTC, MariaTeo commented on src/alez05/mark.pug
> +    div`
you don't need the back-tick

2022-09-07 05:38 UTC, Vivy approved these changes
Good Naruto ref

2022-09-07 09:17 UTC, marianzburlea approved these changes
💯

2022-09-07 11:27 UTC, merged